# permissions for end users to view subjectrolerequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: subjectrolerequest-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: role-keeper
    app.kubernetes.io/part-of: role-keeper
    app.kubernetes.io/managed-by: kustomize
  name: subjectrolerequest-viewer-role
rules:
- apiGroups:
  - rbac.cattle.io
  resources:
  - subjectrolerequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.cattle.io
  resources:
  - subjectrolerequests/status
  verbs:
  - get
